export const MENU_CREATION_REQUEST = 'MENU_CREATION_REQUEST';
export const MENU_CREATION_SUCCESS = 'MENU_CREATION_SUCCESS';
export const MENU_CREATION_FAIL = 'MENU_CREATION_FAIL';
export const MENU_CREATION_RESET = 'MENU_CREATION_RESET';

export const MENU_ITEM_UPDATE_REQUEST = 'MENU_ITEM_UPDATE_REQUEST';
export const MENU_ITEM_UPDATE_SUCCESS = 'MENU_ITEM_UPDATE_SUCCESS';
export const MENU_ITEM_UPDATE_FAIL = 'MENU_ITEM_UPDATE_FAIL';
export const MENU_ITEM_UPDATE_RESET = 'MENU_ITEM_UPDATE_RESET';

export const RESTAURANT_MENU_REQUEST = 'RESTAURANT_MENU_REQUEST';
export const RESTAURANT_MENU_SUCCESS = 'RESTAURANT_MENU_SUCCESS';
export const RESTAURANT_MENU_FAIL = 'RESTAURANT_MENU_FAIL';

export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST';
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS';
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL';

export const MENU_ITEM_DELETE_REQUEST = 'MENU_ITEM_DELETE_REQUEST';
export const MENU_ITEM_DELETE_SUCCESS = 'MENU_ITEM_DELETE_SUCCESS';
export const MENU_ITEM_DELETE_FAIL = 'MENU_ITEM_DELETE_FAIL';
