export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST';
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL';
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT';

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST';
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS';
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL';

export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST';
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS';
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL';
export const RESTAURANT_LIST_RESET = 'RESTAURANT_LIST_RESET';

export const RESTAURANT_UPDATE_PROFILE_REQUEST = 'RESTAURANT_UPDATE_PROFILE_REQUEST';
export const RESTAURANT_UPDATE_PROFILE_SUCCESS = 'RESTAURANT_UPDATE_PROFILE_SUCCESS';
export const RESTAURANT_UPDATE_PROFILE_FAIL = 'RESTAURANT_UPDATE_PROFILE_FAIL';
export const RESTAURANT_UPDATE_PROFILE_RESET = 'RESTAURANT_UPDATE_PROFILE_RESET';

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST';
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS';
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL';
export const RESTAURANT_DETAILS_RESET = 'RESTAURANT_DETAILS_RESET';

export const RESTAURANT_UPDATE_REQUEST = 'RESTAURANT_UPDATE_REQUEST';
export const RESTAURANT_UPDATE_SUCCESS = 'RESTAURANT_UPDATE_SUCCESS';
export const RESTAURANT_UPDATE_FAIL = 'RESTAURANT_UPDATE_FAIL';
export const RESTAURANT_UPDATE_RESET = 'RESTAURANT_UPDATE_RESET';

export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST';
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS';
export const RESTAURANT_DELETE_FAIL = 'RESTAURANT_DELETE_FAIL';

export const RESTAURANT_CREATE_REVIEW_REQUEST = 'RESTAURANT_CREATE_REVIEW_REQUEST';
export const RESTAURANT_CREATE_REVIEW_SUCCESS = 'RESTAURANT_CREATE_REVIEW_SUCCESS';
export const RESTAURANT_CREATE_REVIEW_FAIL = 'RESTAURANT_CREATE_REVIEW_FAIL';
export const RESTAURANT_CREATE_REVIEW_RESET = 'RESTAURANT_CREATE_REVIEW_RESET';

